version: '3.7'

services:
  database:
    image: mongo:4
    container_name: binary-mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
      - "./data/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
    networks:
      - 38_network
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - database
    networks:
      - 38_network
networks:
  38_network:
    driver: bridge
 